# Generated by Django 5.0.6 on 2024-07-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(choices=[('D', 'Disponible'), ('ND', 'No Disponible')], default='D', max_length=2),
        ),
    ]
