# Generated by Django 5.0.6 on 2024-07-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioteca', '0003_remove_libro_estado_libro_disponible_alquiler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='fecha_devolucion',
        ),
    ]
